travis:
  secure:
    BINSTAR_TOKEN: oSvFfOQI2gROsKt2Gmhqeu5n6Zv48mQuEHRk3xk2BI4JBTLdmGN8Dx37lAIXQqzflx9mWnLa+/icy1xC4B+Ir40L2GqU35rIac+i/K3XiVGUg3AgOgBiCc397FuN9gfmtsdW+KQ4DACa0fm/1ln6nysSgkm+DwfzrCE+Egt4FSYpRGDin7R4nOk9nddMy5yyWzxUSzDLLUOAvADV9qLKMCidUZSwWGtUfa4pqLpS4grOaw0xpqsDgHi56yIiXEnUiDtqlmjcB2PbZ709s9p3ZkA8yqhQXNslu8tdgcGZNvo8C+Y5KE+IS8lyPx+8+aEuQG3N8GATfUO+KcZBPWI6SYnbr5IseOpyyG/W+ZFW/7nJIp6spbJQOqJGwYq4qxz013qB5LKY7MheissdyT8QmaIMbGqZgA49x2934XmNYAMRP7JhdaFW+bh4wi2KEWT68r08QhRXCXgsIzkacfApRei7C/0Sr00yy/4FCMICZIcUDOdEEF+4lo5U+/33d3lmVWo0YcE4piOsfU+5VaLC2qsQf4r3w3/k4QpPtjEjAc0WDEpiYzuwVlr/yzStIDSMkmuf7y3XPCFY6topSC5hpMmMkz4Ynips8TFaRQm0e+PE+bDlJbfKNVhK8G0zwJFbIhJD+nCaAyY9X32v0b1dynk19Yhefxp+HZevtWZG768=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
